name: CI

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute
    # Uncomment the line below to run every two minutes
    # - cron: '*/2 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  runwhenbuildcomplete:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: run for run
        run: echo "fun"

  runwhenbuildcompleteafter:
    runs-on: ubuntu-latest
    needs: [runwhenbuildcomplete, build]
    steps:
      - name: run for run
        run: echo "fun"
